### ISSUE TITLE
Can additional repositories be set for rhub_check()?

### ISSUE THREAD

**Issue by florisvdh** [r-hub/actions#22]
When running `rhub_check()`, dependencies from `Additional_repositories` (in `DESCRIPTION`) cannot be installed and the workflow errors in the `setup-deps` step.

In the `other-platforms` job of `rhub.yaml`,  I tried inserting below step, right before the `platform-info` step, but it seems the `repos` option doesn't take effect.

```yaml
      - name: Add additional r-universe repository
        run: |
          # Add additional r-universe repository
          options(repos = c(getOption("repos"), "https://geocompr.r-universe.dev"))
        shell: Rscript {0}
```

For the `linux-containers` I see no obvious way.

May relate to https://github.com/r-lib/pak/issues/424.

**Comment by gaborcsardi** [comment]
If you call `options()` in an R session that does not apply to future R sessions. You need to write it into the `~/.Rprofile` file.

**Comment by florisvdh** [comment]
Thanks!

Updated to:

```yaml
      - name: Add additional r-universe repository
        run: |
          # Add additional r-universe repository
          echo 'options(repos = c(getOption("repos"), "https://geocompr.r-universe.dev"))' >> ~/.Rprofile
        shell: bash
```

Works in the Linux containers, works on macos! Still not on Windows it seems. Maybe `.Rprofile` file is put in the wrong place here.
